[package]
name = "schred"
version = "0.1.0"
edition = "2021"

[lib]
name = "schred"
path = "src/lib.rs"

[[bin]]
name = "schred"
path = "src/bin.rs"

[dependencies]

[dev-dependencies]
rand = "0.8.5"
