[package]
name = "schred-lib"
version = "0.1.0"
edition = "2021"

[lib]
name = "schred-lib"
path = "src/lib.rs"

[dependencies]
rand_core = { version = "0.6.4",  features = ["getrandom"] }

[dev-dependencies]
rand = "0.8.5"
serial_test = "2.0.0"
